// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath =
    process.argv[2] ??
    resolve(
        packageDirectory,
        "src",
        "otel",
        "generated",
        "sourceVersionBuild.ts",
    );

const headRevision =
    normalize(process.env.TYPEAGENT_BUILD_HEAD_REVISION) ??
    readGit(["rev-parse", "HEAD"]);
const baseRevision =
    normalize(process.env.TYPEAGENT_BUILD_BASE_REVISION) ??
    readGit(["merge-base", "HEAD", "origin/main"]);

const sourceVersion = {
    ...(headRevision === undefined ? {} : { headRevision }),
    ...(baseRevision === undefined ? {} : { baseRevision }),
};

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
    outputPath,
    `// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Generated by scripts/writeSourceVersion.mjs. Do not edit.
export const BUILD_SOURCE_VERSION = Object.freeze(${JSON.stringify(sourceVersion, undefined, 4)} as const);
`,
    "utf8",
);

function normalize(value) {
    const normalized = value?.trim();
    return normalized ? normalized : undefined;
}

function readGit(args) {
    try {
        return normalize(
            execFileSync("git", args, {
                cwd: packageDirectory,
                windowsHide: true,
                encoding: "utf8",
                timeout: 5_000,
            }),
        );
    } catch {
        return undefined;
    }
}
