// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { ActivityContext } from "./agentInterface.js";
import { DisplayContent } from "./display.js";
import { Entity } from "./memory.js";

export interface AppAction {
    actionName: string;
    schemaName?: string;
    parameters?: Record<string, unknown>; // the type of the parameters are defined by the AppAgent
}

export type ActionResultError = {
    error: string;
    fallbackToReasoning?: boolean | undefined;
};

// LLM token usage an agent may attribute to executing an action/command.
// Structurally compatible with aiclient's `CompletionUsageStats` and the
// dispatcher's `CompletionUsageStats` — duplicated here so agent-sdk stays
// dependency-free. Agents that make LLM calls SHOULD report this so the UI
// can show "Action Tokens". Leaving it `undefined` means "not reported /
// unknown" — which is distinct from a reported value of 0 (no LLM call).
export type ActionTokenUsage = {
    completion_tokens: number;
    prompt_tokens: number;
    total_tokens: number;
};

export type ActionResultActivityContext = Omit<
    ActivityContext,
    "appAgentName"
> | null;

export type PendingYesNoChoice = {
    choiceId: string;
    type: "yesNo";
    message: string;
};

export type PendingMultiChoice = {
    choiceId: string;
    type: "multiChoice";
    message: string;
    choices: string[];
};

/**
 * A single-select pick combined with a "remember this" checkbox. Rendered as
 * one card: the user clicks one of `choices` and optionally checks the
 * `checkboxLabel` box. The response is a `PickRememberResponse`.
 */
export type PendingPickRememberChoice = {
    choiceId: string;
    type: "pickRemember";
    message: string;
    choices: string[];
    checkboxLabel: string;
};

export type PendingChoice =
    | PendingYesNoChoice
    | PendingMultiChoice
    | PendingPickRememberChoice;

export type ActionResultSuccess = {
    historyText?: string | undefined;
    displayContent: DisplayContent; // the display content to be appended with "block" mode
    entities: Entity[];
    resultEntity?: Entity | undefined;
    dynamicDisplayId?: string | undefined;
    dynamicDisplayNextRefreshMs?: number | undefined;
    additionalInstructions?: string[] | undefined;
    additionalActions?: AppAction[];
    error?: undefined;

    // REVIEW: activityContext needs to be declarative in the schema instead of generated by the action themselves
    activityContext?: ActionResultActivityContext; // null to clear the activity context
    pendingChoice?: PendingChoice | undefined;

    // LLM token usage the agent consumed producing this result. Optional;
    // `undefined` => not reported. A reported value of all-zero => the agent
    // ran but made no LLM call. Accumulated by the dispatcher across all
    // actions in a request and surfaced as "Action Tokens" in the UI.
    tokenUsage?: ActionTokenUsage | undefined;
};

export type ActionResultSuccessNoDisplay = Omit<
    ActionResultSuccess,
    "displayContent"
> & {
    displayContent?: undefined;
};

export type ActionResult =
    | ActionResultSuccessNoDisplay
    | ActionResultSuccess
    | ActionResultError;

type EntityField<T> = T extends string
    ? Entity
    : T extends any[]
      ? (EntityField<Required<T[number]>> | undefined)[]
      : T extends object
        ? EntityMap<T>
        : undefined;

export type EntityMap<T> = {
    [Property in keyof T]?: EntityField<T[Property]>;
};

export type ActionEntities<T extends AppAction = AppAction> =
    T["parameters"] extends undefined
        ? undefined
        : EntityMap<Required<T["parameters"]>>;

export type TypeAgentAction<
    T extends AppAction = AppAction,
    Name extends string = string,
> = T extends AppAction
    ? T & {
          schemaName: Name;
          entities?: ActionEntities<T>;
      }
    : never;
