packages:
  - packages/*
  - packages/memory/*
  - packages/agents/*
  - packages/agents/agentUtils/*
  - examples/*
  - examples/agentExamples/*
  - tools
onlyBuiltDependencies:
  - "@azure/msal-node-extensions"
  - "@azure/msal-node-runtime"
  - "@vscode/vsce-sign"
  - better-sqlite3
  - electron
  - esbuild
  - exifreader
  - keytar
  - puppeteer
