forceLegacyDeploy: true
packages:
  - packages/*
  - packages/memory/*
  - packages/agents/*
  - packages/agents/agentUtils/*
  - packages/agentServer/*
  - packages/dispatcher/*
  - packages/utils/*
  - packages/mcp/*
  - examples/*
  - examples/agentExamples/*
  - tools

onlyBuiltDependencies:
  - "@azure/msal-node-extensions"
  - "@azure/msal-node-runtime"
  - "@vscode/vsce-sign"
  - better-sqlite3
  - canvas
  - electron
  - electron-winstaller
  - esbuild
  - exifreader
  - keytar
  - koffi
  - puppeteer
  - sharp
