# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
  branches:
    include:
      - main

pr:
  branches:
    exclude:
      - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: buildDirectory
    value: $(Build.SourcesDirectory)/ts
  - name: packageDirectory
    value: $(Build.ArtifactStagingDirectory)/packages
  - name: publishedPackageDirectory
    value: $(Build.ArtifactStagingDirectory)/packages/published
  - name: NpmRcDirectory
    value: $(Build.SourcesDirectory)
jobs:
  - job: build_ts
    displayName: "Build TypeScript Project"
    strategy:
      matrix:
        node_22:
          nodeVersion: "22"
    steps:
      - template: include-prepare-repo.yml
        parameters:
          buildDirectory: $(buildDirectory)
          nodeVersion: $(nodeVersion)
          registry: $(REGISTRY)

      - template: include-update-package-version.yml
        parameters:
          packageFolder: $(buildDirectory)
          prerelease: $(Build.BuildId)

      - script: |
          npm run build
        displayName: "Build"
        workingDirectory: $(buildDirectory)

      - script: |
          pnpm pack --filter @typeagent/* --pack-destination $(publishedPackageDirectory)
        displayName: "Pack Published packages"
        workingDirectory: $(buildDirectory)

      - script: |
          pnpm pack --filter=\!@typeagent/* --pack-destination $(packageDirectory)
        displayName: "Pack Non-published packages"
        workingDirectory: $(buildDirectory)

      - publish: $(packageDirectory)
        artifact: Packages

      - script: |
          sudo apt install libsecret-1-0
        displayName: "Install libsecret-1-0"
        condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

      - script: |
          npm run test:local
        displayName: "Run Tests (Local)"
        workingDirectory: $(buildDirectory)

      - script: |
          npm run lint
        displayName: "Lint"
        workingDirectory: $(buildDirectory)

      - script: |
          npm run check:policy
        displayName: "Check Policy"
        workingDirectory: $(buildDirectory)

      - script: |
          echo $(ADO_REGISTRY)
          echo "registry=$(ADO_REGISTRY)" > .npmrc
          echo "always-auth=true" >> .npmrc
          cat .npmrc
        displayName: "Create .npmrc file."
        workingDirectory: $(NpmRcDirectory)

      - task: npmAuthenticate@0
        inputs:
          workingFile: "$(NpmRcDirectory)/.npmrc"
        displayName: "Authenticate with Azure Artifacts"

      - script: |
          for file in $(publishedPackageDirectory)/*.tgz; do
            echo "Publishing file: $file"
            npm publish --registry=$(ADO_REGISTRY) "$file"
          done
        displayName: "Publish packages"
        workingDirectory: $(NpmRcDirectory)
