// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Sub-schema: channelManagement — Actions related to creating, modifying, and managing channels.
// Auto-generated by the onboarding scaffolder.

export type ChannelManagementActions =
    | GetChannelAction
    | ModifyChannelAction
    | SetVoiceChannelStatusAction
    | DeleteChannelAction
    | EditChannelPermissionsAction
    | GetChannelInvitesAction
    | CreateChannelInviteAction
    | DeleteChannelPermissionAction
    | FollowAnnouncementChannelAction
    | GroupDMAddRecipientAction
    | GroupDMRemoveRecipientAction;
