// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Sub-schema: guildManagement — Actions related to creating and managing guilds.
// Auto-generated by the onboarding scaffolder.

export type GuildManagementActions = CreateGuildAction | GetGuildAction;
