// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Sub-schema: inviteManagement — Actions related to creating and managing invites.
// Auto-generated by the onboarding scaffolder.

export type InviteManagementActions = GetInviteAction | DeleteInviteAction;
