// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Sub-schema: messageManagement — Actions related to creating and managing messages and webhooks.
// Auto-generated by the onboarding scaffolder.

export type MessageManagementActions =
    | CreateMessageAction
    | CreateWebhookAction
    | GetWebhookAction
    | ExecuteWebhookAction
    | TriggerTypingIndicatorAction;
