// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Sub-schema: threadManagement — Actions related to creating and managing threads within channels.
// Auto-generated by the onboarding scaffolder.

export type ThreadManagementActions =
    | StartThreadFromMessageAction
    | StartThreadWithoutMessageAction
    | StartThreadInForumOrMediaChannelAction
    | JoinThreadAction
    | AddThreadMemberAction
    | LeaveThreadAction
    | RemoveThreadMemberAction
    | GetThreadMemberAction
    | ListThreadMembersAction
    | ListPublicArchivedThreadsAction
    | ListPrivateArchivedThreadsAction
    | ListJoinedPrivateArchivedThreadsAction;
