// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Sub-schema: userManagement — Actions related to managing users and their roles.
// Auto-generated by the onboarding scaffolder.

export type UserManagementActions =
    | GetUserAction
    | GetTargetUsersAction
    | UpdateTargetUsersAction
    | GetTargetUsersJobStatusAction
    | GetApplicationRoleConnectionMetadataRecordsAction
    | UpdateApplicationRoleConnectionMetadataRecordsAction;
