# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This workflow will build the TypeAgent TypeScript code.

name: build-dotnet

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: read
  contents: read

jobs:
  build_dotnet:
    strategy:
      fail-fast: false
      matrix:
        configuration: ["Debug", "Release"]
    runs-on: "windows-latest"
    steps:
      - name: Setup Git LF
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        continue-on-error: true
        with:
          filters: |
            dotnet:
              - "dotnet/**"
              - "ts/packages/agents/desktop/src/**Schema.ts"
              - ".github/workflows/build-dotnet.yml"
      - name: Setup MSBuild
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      - name: Setup NuGet
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        uses: NuGet/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4.0
      - name: Install pnpm
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          package_json_file: ts/package.json
      - name: Setup Node.js
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: ts/pnpm-lock.yaml
      - name: Install TS dependencies and generate schemas
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        working-directory: ts
        run: |
          pnpm install --frozen-lockfile --strict-peer-dependencies
          pnpm run --filter @typeagent/action-schema-compiler... build
          pnpm run -C packages/agents/desktop asc:all
      - name: Restore Packages (AutoShell)
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        working-directory: dotnet
        run: nuget restore autoShell/AutoShell.sln
      - name: Build Solution (AutoShell)
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        working-directory: dotnet
        run: |
          msbuild.exe autoShell/AutoShell.sln /p:platform="Any CPU" /p:configuration="${{ matrix.configuration }}"
      - name: Test AutoShell
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        working-directory: dotnet/autoShell.Tests
        run: dotnet test --configuration ${{ matrix.configuration }}
      - name: Restore Packages (TypeAgent)
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        working-directory: dotnet
        run: nuget restore typeagent/TypeAgent.sln
      - name: Build Solution (TypeAgent)
        if: ${{ github.event_name != 'pull_request' || steps.filter.outputs.dotnet != 'false' }}
        working-directory: dotnet
        run: msbuild.exe typeagent/TypeAgent.sln /p:platform="Any CPU" /p:configuration="${{ matrix.configuration }}"
